Authentification/urls.py
from django.urls import path
from django.urls import include
from .import views
from .views import CustomLoginView

app_name='Authentification'

urlpatterns = [
    #login
    path('login',CustomLoginView.as_view(), name='login'),
   
    #signup
    path('register', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('',views.home, name='home'),
    # path('admin/login/', CustomLoginView.as_view(), name='login'),
    
    path('profil/', views.profil_view, name='profil'),
]

Enseignant/urls.py
from django.urls import path
from .import views
app_name="Enseignant"
urlpatterns=[
    path('',views.index,name='index'),
    path('enseigant_profile',views.enseigant_profile,name='enseigant_profile'),
    path('Composer',views.Composer,name='Composer'),
    path('Envoyer',views.Envoyer,name='Envoyer'),
    path('Corriger',views.Corriger,name='Corriger'),
]

Etudiant/urls.py
from django.urls import path
from .import views
app_name="Etudiant"
urlpatterns=[
    path('',views.index,name='index'),
    path('Mes_copies',views.Mes_copies,name='Mes_copies'),
    path('Fichier_Personnel',views.Fichier_Personnel,name='Fichier_Personnel'),
    path('Profil',views.Profil,name='Profil'),
    
]

Enseignant/models.py
from django.db import models
from Authentification.models import CustomUser
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model



# Create your models here.
    #Enseignant
class EnseignantModels(CustomUser):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='enseignant_profile', default=None, blank=True, null=True)
    specialite = models.CharField(max_length=100, verbose_name='Specialite')
    
    class Meta:
        verbose_name = "Enseignant"
        verbose_name_plural = "Enseignants"

    def save(self, *args, **kwargs):
        if not self.pk:  # Lors de la création initiale
            self.password = make_password(self.password)
        super(EnseignantModels, self).save(*args, **kwargs)
        
# class EnvoiCopieCorrigee(DossierImageTif):
    
#     enseignant = models.ForeignKey(EnseignantModels, on_delete=models.CASCADE,default =None)
#     scolarite = models.ForeignKey(ScolariteModels, on_delete=models.CASCADE, default='', blank=True, null=True)
    
#     enseignant_nom = models.CharField(max_length=100,default='')
#     enseignant_prenom = models.CharField(max_length=100,default='')
#     module = models.CharField(max_length=100, verbose_name='Module',default='')
#     promotion = models.CharField(max_length=100,verbose_name='Promotion',default='')
#     niveau = models.CharField(max_length=100, verbose_name='Niveau',default='')
#     nombre = models.IntegerField(verbose_name='Nombre de copies',default='')
#     dossier = models.FileField(upload_to='uploads/', max_length=100)
#     date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
       return f"{self.matricule}-{self.name}-{self.prenom}"

ScolaritePersonal/models.py
from django.db import models
from Authentification.models import CustomUser
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model

from Enseignant.models import EnseignantModels



# Create your models here.

    #Scolarite
class ScolariteModels(CustomUser):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='scolarite_profile', default=None, blank=True, null=True)    
    fonction = models.CharField(max_length=100, verbose_name='Emploi/Fonction')
    etablissement = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = "Scolarite"
        verbose_name_plural = "Scolarites"

    def save(self, *args, **kwargs):
        if not self.pk:  # Lors de la création initiale
            self.password = make_password(self.password)
        super(ScolariteModels, self).save(*args, **kwargs)
        
class DossierImageTif(models.Model):
    enseignant = models.ForeignKey(EnseignantModels, on_delete=models.CASCADE,default =None,null=True)
    scolarite = models.ForeignKey(ScolariteModels, on_delete=models.CASCADE, default='', blank=True, null=True)
    
    enseignant_nom = models.CharField(max_length=100,default='')
    enseignant_prenom = models.CharField(max_length=100,default='')
    module = models.CharField(max_length=100, verbose_name='Module',default='')
    promotion = models.CharField(max_length=100,verbose_name='Promotion',default='')
    niveau = models.CharField(max_length=100, verbose_name='Niveau',default='')
    nombre = models.IntegerField(verbose_name='Nombre de copies',default='')
    dossier = models.FileField(upload_to='uploads/', max_length=100)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.dossier.name} - {self.enseignant.username} {self.enseignant.prenom}"

Enseignant/views.py
from django.utils import timezone
import os
import zipfile
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from Enseignant.models import EnseignantModels
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.core.files.base import ContentFile

from GestionDesCopies import settings
from ScolaritePersonal.forms import DossierImageForms
from ScolaritePersonal.models import DossierImageTif, ScolariteModels


# Create your views here.
@login_required(login_url='Authentification:login')
def index (request):
    # Récupérer l'utilisateur connecté (enseignant)
    enseignant = request.user

    # Récupérer les copies reçues par l'enseignant
    copies_recues = DossierImageTif.objects.filter(enseignant=enseignant).order_by('-date')

    context = {
        'copies_recues': copies_recues
    }
    return render(request,"enseignant/index.html",context)


def handle_uploaded_files(files, folder_path):
    zip_subfolder_path = os.path.join(folder_path, 'copies.zip')
    with zipfile.ZipFile(zip_subfolder_path, 'w') as zipf:
        for f in files:
            file_path = os.path.join(folder_path, f.name)
            with open(file_path, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            zipf.write(file_path, os.path.basename(file_path))
            os.remove(file_path)  # Optionally remove the original files
    return zip_subfolder_path

@login_required(login_url='Authentification:login')
def Envoyer(request):
    if request.method == 'POST':
        form = DossierImageForms(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('dossier')
            scolarite_matricule = form.cleaned_data['enseignant_matricule']#ici c'est plutot scolarité_matricule qui sera recuperer
            
            try:
                scolarite = ScolariteModels.objects.get(matricule=scolarite_matricule)
            except ScolariteModels.DoesNotExist:
                message = f"Aucun enseignant trouvé avec le matricule {scolarite_matricule}."
                return render(request, 'copie/copie_envoyee.html', {'message': message})

            # Crée un dossier pour l'enseignant
            folder_name = f'{scolarite_matricule}_{scolarite.username}'
            folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads', folder_name)

            if not os.path.exists(folder_path):
                os.makedirs(folder_path)

            # Gérer le fichier uploadé
            zip_file_path = handle_uploaded_files(files, folder_path)

            # Obtenir l'instance de ScolariteModels de l'utilisateur connecté
            
            #scolarite = ScolariteModels.objects.get(user=request.user)
            
                # message = 'Aucune scolarité associée à cet utilisateur.'
                # return render(request, 'copie/copie_envoyee.html', {'message': message})
            
            #logger.debug(f'Scolarite: {scolarite}')

            # Créer l'objet DossierImageTif
            DossierImageTif.objects.create(
                dossier=ContentFile(open(zip_file_path, 'rb').read(), 'copies.zip'),
                scolarite=scolarite,
                module=form.cleaned_data['module'],
                promotion=form.cleaned_data['promotion'],
                niveau=form.cleaned_data['niveau'],
                nombre=form.cleaned_data['nombre'],
                #enseignant_nom=form.cleaned_data['enseignant_nom'],
                #enseignant_prenom=form.cleaned_data['enseignant_prenom'],
                date=timezone.now(),
                #scolarite=scolarite  # Enregistrer l'utilisateur connecté
            ) 
            # Message de succès
            success_message = f"Copie envoyée avec succès à {scolarite.username} {scolarite.prenom}."
            messages.success(request, success_message)
            
            return redirect('Enseignant:Envoyer')
        else:
            messages.error(request, "Veuillez vérifier les informations du formulaire.")
    else:
        form = DossierImageForms()

    return render(request, "Copie/envoyer_copie.html", {'form': form})


def enseigant_profile (request):

    return render(request,"Profil/enseigant_profile.html")

def Composer (request):

    return render(request,"Copie/compos_copie.html")


def Corriger (request):
     
    return render(request,"Copie/corriger_copie.html")

Enseignant/templates/Copie/compos_copie.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Composer-Sujet {% endblock %}

{% block content %}

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:index'%}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login'%}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Envoyer' %}">
                <i class="bi bi-journal-text"></i>
                <span>Envoyer Copies</span>
            </a>
        </li><!-- End Forms Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Composer' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Composer une évaluation</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Corriger' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Corriger une évaluation</span>
            </a>
        </li><!-- End Tables Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:enseigant_profile' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->
    <main id="main" class="main">
        <div class="pagetitle">
            <h6><span class="d-none d-lg-block">Gestion des copies d'étudiants de l'Université Norbert ZONGO</span></h6>
            
            <h1>Enseignant de l'UNZ</h1>
            <nav>
                
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'Enseignant:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard-Enseignant</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section profile">
            <div class="container mt-5">
                <div class="container mt-5">
                    <h2> Composer une evaluation</h2>
                    <form class=" p-4 shadow" style="width: 80%;">
                        <div class="mb-3">
                            <label for="nom" class="form-label">Nom</label>
                            <input type="text" name="Matriclue" class="form-control" id="nom" required>
                        </div>

                        <div class="mb-3">
                            <label for="mail" class="form-label">Adresse</label>
                            <input type="email" name="mail" class="form-control" id="mail" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="siege" class="form-label">Siège</label>
                            <input type="text" name="siege" class="form-control" id="siege" required>
                        </div>

                        <div class="mb-3">
                            <label for="activity" class="form-label">Activité</label>
                            <input type="text" name="activity" class="form-control" id="activity" required>
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-warning shadow">
                                <i class="bi bi-pencil"></i> Modifier</button>
                        </div>
                    </form>
                    <br>
                    <h3>Cette fonctionalité du site n'est pas effective pour le moment. <a href="{% url 'Enseignant:index' %}" class="badge bg-success">Retour</a></h3>
                  </div>
        </section>
                                           
    </main><!-- End #main -->

{% endblock %}

Enseignant/templates/Copie/corriger_copie.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Composer-Sujet {% endblock %}

{% block content %}

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:index'%}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Envoyer' %}">
                <i class="bi bi-journal-text"></i>
                <span>Envoyer Copies</span>
            </a>
        </li><!-- End Forms Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Composer' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Composer une évaluation</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Corriger' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Corriger une évaluation</span>
            </a>
        </li><!-- End Tables Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:enseigant_profile' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->
    <main id="main" class="main">
        <div class="pagetitle">
            <h6><span class="d-none d-lg-block">Gestion des copies d'étudiants de l'Université Norbert ZONGO</span></h6>
            
            <h1>Enseignant de l'UNZ</h1>
            <nav>
                
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'Enseignant:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard-Enseignant</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section profile">
            <div class="container mt-5">
                <div class="container mt-5">
                    <h2> Corrige une evaluation</h2>
                    <form class=" p-4 shadow" style="width: 80%;">
                        <div class="mb-3">
                            <label for="nom" class="form-label">Nom</label>
                            <input type="text" name="Matriclue" class="form-control" id="nom" required>
                        </div>

                        <div class="mb-3">
                            <label for="mail" class="form-label">Adresse</label>
                            <input type="email" name="mail" class="form-control" id="mail" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="siege" class="form-label">Siège</label>
                            <input type="text" name="siege" class="form-control" id="siege" required>
                        </div>

                        <div class="mb-3">
                            <label for="activity" class="form-label">Activité</label>
                            <input type="text" name="activity" class="form-control" id="activity" required>
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-warning shadow">
                                <i class="bi bi-pencil"></i> Modifier</button>
                        </div>
                    </form>
                    <br>
                    <h3>Cette fonctionalité du site n'est pas effective pour le moment. <a href="{% url 'Enseignant:index' %}" class="badge bg-success">Retour</a></h3>
                  </div>
        </section>
                                           
    </main><!-- End #main -->

{% endblock %}

Enseignant/templates/Copie/envoyer_copie.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Envoyer-Sujet {% endblock %}

{% block content %}
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:index'%}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login'%}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Envoyer' %}">
                <i class="bi bi-journal-text"></i>
                <span>Envoyer Copies</span>
            </a>
        </li><!-- End Forms Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Composer' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Composer une évaluation</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:Corriger' %}">
                <i class="bi bi-menu-button-wide"></i>
                <span>Corriger une évaluation</span>
            </a>
        </li><!-- End Tables Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Enseignant:enseigant_profile' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->

<main id="main" class="main">
    <div class="pagetitle">
        <h6><span class="d-none d-lg-block">Gestion des copies d'étudiants de l'Université Norbert ZONGO</span></h6>
        
        <h1>Enseignant de l'UNZ</h1>
        <nav>
            
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'Enseignant:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Dashboard-Enseignant</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

        <section class="section profile">
            <div class="container mt-5">
                <div class="container mt-5">
                    <h2> Envoyer copies corrigées </h2>
                    {% comment %} <form class=" p-4 shadow" style="width: 80%;">
                        <div class="mb-3">
                            <label for="nom" class="form-label">Fillière</label>
                            <input type="text" name="Matriclue" class="form-control" id="nom" required>
                        </div>

                        <div class="mb-3">
                            <label for="mail" class="form-label">Promotion</label>
                            <input type="email" name="mail" class="form-control" id="mail" required>
                        </div>
                        
                        <div class="mb-3">
                            <label for="siege" class="form-label">Module</label>
                            <input type="text" name="siege" class="form-control" id="siege" required>
                        </div>

                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre de copie</label>
                            <input type="number" name="nombre" class="form-control" id="nombre" required>
                        </div>
                        <div class="mb-3">
                            <label for="enseignant" class="form-label">Enseignant</label>
                            <input type="text" name="enseignant" class="form-control" id="enseignant" required>
                        </div>
                        <div class="mb-3">
                            <label for="ufr" class="form-label">UFR/Scolarite</label>
                            <input type="text" name="ufr" class="form-control" id="ufr" required>
                        </div>
                        <div class="mb-3">
                            <label for="fileInput" class="form-label">Sélectionner un fichier :</label>
                            <input type="file" class="form-control" id="fileInput" name="file">
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-warning shadow">
                                <i class="bi bi-send-fill"></i> Envoyer</button>
                        </div>
                    </form> {% endcomment %}
                    {% if messages %}
                    <div class="alert-messages">
                        {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                    <form method="post" enctype="multipart/form-data" class="form-control" class=" p-4 shadow">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            {% comment %} <input type="file" id="fileInput" name="dossier" webkitdirectory directory multiple /> {% endcomment %}
                            <input multiple type="file" name="dossier" id="id_dossier" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </form>
                    {% if message %}
                        <p>{{ message }}</p>
                    {% endif %}
                    <script>
                        document.getElementById('fileInput').addEventListener('change', function(event) {
                            let files = event.target.files;
                            let formData = new FormData();
                            for (let file of files) {
                                formData.append('dossier', file);
                            }
                            document.getElementById('uploadForm').onsubmit = function() {
                                for (let [key, value] of formData.entries()) {
                                    this.appendChild(new File([value], key));
                                }
                            }
                        });
                    </script>
                    <script>
                        document.addEventListener('DOMContentLoaded', function() {
                            var dateField = document.getElementById('date_field');
                            var now = new Date();
                            var formattedDate = now.toISOString().slice(0, 19).replace('T', ' ');
                            dateField.value = formattedDate;
                        });
                    </script>
                  </div>
        </section>
                                           
</main><!-- End #main -->

{% endblock %}