Authentification/urls.py
from django.urls import path
from django.urls import include
from .import views
from .views import CustomLoginView

app_name='Authentification'

urlpatterns = [
    #login
    path('login',CustomLoginView.as_view(), name='login'),
   
    #signup
    path('register', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('',views.home, name='home'),
    # path('admin/login/', CustomLoginView.as_view(), name='login'),
    
    path('profil/', views.profil_view, name='profil'),
]

Etudiant/urls.py
from django.urls import path
from .import views
app_name="Etudiant"
urlpatterns=[
    path('',views.index,name='index'),
    path('Mes_copies',views.Mes_copies,name='Mes_copies'),
    path('Fichier_Personnel',views.Fichier_Personnel,name='Fichier_Personnel'),
    path('Profil',views.Profil,name='Profil'),
    
]

Etudiant/models.py
from django.db import models
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _
from Authentification.models import CustomUser
from django.contrib.auth import get_user_model



class EtudiantModels(CustomUser):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='etudiant_profile', default=None, blank=True, null=True)
    etudiant_filiere = models.CharField(max_length=100, default=None, verbose_name='Filière', blank=True, null=True)
    etudiant_niveau = models.CharField(max_length=5, default=None, verbose_name='Niveau', blank=True, null=True)
    etudiant_promotion = models.CharField(max_length=100, default=None, verbose_name='Promotion', blank=True, null=True)

    class Meta:
        verbose_name = "Etudiant"
        verbose_name_plural = "Etudiants"
        
    def __str__(self):
        if self.user:
            return f"{self.user.matricule} - {self.user.prenom} {self.user.name} - {self.etudiant_filiere} - {self.etudiant_promotion} - {self.etudiant_niveau}"
        return "Sans Matricule"
        
    def save(self, *args, **kwargs):
        if not self.pk and self.password:
            self.password = make_password(self.password)
        super(EtudiantModels, self).save(*args, **kwargs)


# models.py


class StudentFile(models.Model):
    student = models.ForeignKey(EtudiantModels, on_delete=models.CASCADE, related_name='student_files', default=None, blank=True, null=True)
    fichier = models.FileField(upload_to='student_files/',max_length=255)
    module = models.CharField(max_length=100, verbose_name='Module',default='')

    telechargement_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.username} - {self.fichier.name}"

Etudiant/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from Authentification import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from Etudiant.models import EtudiantModels, StudentFile
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    student_files_list = StudentFile.objects.filter(student=request.user).order_by('-telechargement_date')
    paginator = Paginator(student_files_list, 10)  # 10 fichiers par page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'student_files_list': page_obj
    }
    return render(request, "etudiant/index.html", context)


def Mes_copies (request):
    
    return render(request,"copie/mes_copies.html")

def Fichier_Personnel (request):
    
    return render(request,"dossier/fichier_personel.html")

def Profil (request):
    
    return render(request,"Profil/etudiant_profil.html")

Etudiant/templates/dossier/fichier_personel.html
{% extends "base.html" %}

{% block title %} Dashboard Etudiant {% endblock %}

{% block content %}

<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Etudiant:index' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Etudiant:Mes_copies' %}">
                <i class="bi bi-copy"></i>
                <span>Mes Copies</span>
            </a>
        </li><!-- End Forms Nav -->

   
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Etudiant:Fichier_Personnel' %}">
                <i class="bi bi-files"></i>
                <span>Fichiers Personnels</span>
            </a>
        </li><!-- End Tables Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Etudiant:Profil' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->


<main id="main" class="main">

    <div class="pagetitle">
        <h6><span class="d-none d-lg-block">Gestion des copies d'étudiants de l'Université Norbert ZONGO</span></h6>
        <h1>MPCI | 2021-2022</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'Etudiant:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Mes Fichiers</li>
                <li class="breadcrumb-item active">Dashboard-Enseignant</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section profile">
        <div class="container mt-5">
            <div class="container mt-5">
                <h2> Mes fichiers Personnels</h2>
                <form class=" p-4 shadow" style="width: 80%;">
                    <div class="mb-3">
                        <label for="fileInput" class="form-label">Sélectionner un fichier :</label>
                        <input type="file" class="form-control" id="fileInput" name="file">
                    </div>
                    <div id="dropArea" class="drop-area">
                        <input type="file" id="fileInput" multiple>
                        <p class="mb-5 bg-white">Glissez-déposez des fichiers ici ou cliquez pour sélectionner des fichiers.</p>
                        <div id="fileList"></div>
                    </div>
                    
                    <div class="col-12">
                        <button type="submit" class="btn btn-success shadow">
                            <i class="bi bi-send-fill"></i> Enregistrer</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</main><!-- End #main -->

{% endblock %}