Authentification/urls.py
from django.urls import path
from django.urls import include
from .import views
from .views import CustomLoginView

app_name='Authentification'

urlpatterns = [
    #login
    path('login',CustomLoginView.as_view(), name='login'),
   
    #signup
    path('register', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('',views.home, name='home'),
    # path('admin/login/', CustomLoginView.as_view(), name='login'),
    
    path('profil/', views.profil_view, name='profil'),
]

Etudiant/urls.py
from django.urls import path
from .import views
app_name="Etudiant"
urlpatterns=[
    path('',views.index,name='index'),
    path('Mes_copies',views.Mes_copies,name='Mes_copies'),
    path('Fichier_Personnel',views.Fichier_Personnel,name='Fichier_Personnel'),
    path('Profil',views.Profil,name='Profil'),
    
]

UserPrincipale/urls.py
from django.urls import path
from .import views

app_name='userprincipale'

urlpatterns=[
    path('',views.index,name='index'),
    path('usersprofile/', views.usersprofile, name='usersprofile'),
    path('admin_static/',views.Admin_static, name='admin_static'),
    
    #Enseignant
    path('Enseignant/', views.enseignant, name='enseignant'),
    path('ajouter/', views.ajouter, name='ajouter'),
    path('editer/<str:matricule>/', views.editer, name='editer'),
    path('supprimer/<str:matricule>/', views.supprimer, name='supprimer'),
    
    #Scolarité
    path('Scolarite/', views.scolarity, name='scolarity'),
    path('sc_ajouter/', views.sc_ajouter, name='sc_ajouter'),
    path('sc_editer/<str:matricule>/', views.sc_editer, name='sc_editer'),
    path('sc_supprimer/<str:matricule>/', views.sc_supprimer, name='sc_supprimer'),
    
    #Etudiant// Afficher les etudiants sur le dashbord de l'admin
    path('Etudiant/', views.etudiant, name='etudiant'),
]

UserPrincipale/forms.py
from django import forms
from Etudiant.models import EtudiantModels
from Enseignant.models import EnseignantModels
from ScolaritePersonal.models import ScolariteModels

class ScolariteForm(forms.ModelForm):
    class Meta:
        model = ScolariteModels
        fields = ['matricule', 'username', 'prenom', 'fonction', 'etablissement', 'email']
        
class EnseignantForm(forms.ModelForm):
    class Meta:
        model = EnseignantModels
        fields = ['matricule', 'username', 'prenom', 'specialite', 'email']
        
class EtudiantForm(forms.ModelForm):
    class Meta:
        model = EtudiantModels
        fields = ['matricule', 'username', 'prenom', 'etudiant_filiere','etudiant_promotion','etudiant_niveau','email']

UserPrincipale/views.py
from django.shortcuts import render, redirect, get_object_or_404
from Etudiant.models import EtudiantModels
from Enseignant.models import EnseignantModels
from django.contrib import messages
from ScolaritePersonal.models import ScolariteModels
from .forms import ScolariteForm, EnseignantForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth import get_user_model


@csrf_protect
@user_passes_test(lambda u: u.is_superuser)
def index(request):

    return render(request, "userprincipale/index.html")

#enseignant
def enseignant(request):
    query = request.GET.get('q')
    if query:
        enseignants = EnseignantModels.objects.filter(
            Q(matricule__icontains=query) |
            Q(username__icontains=query) |
            Q(prenom__icontains=query) |
            Q(specialite__icontains=query)
        )
    else:
        enseignants = EnseignantModels.objects.all()

    message = messages.get_messages(request)

    context = {'enseignants': enseignants, 
               'message': message}
    return render(request, "Enseignant/enseignant.html", context)


    
def ajouter(request):
    error=False
    message=""
    if request.method == 'POST':
        # Récupérer les données soumises par l'utilisateur
        matricule = request.POST.get('matricule')
        username = request.POST.get('username')
        prenom = request.POST.get('prenom')
        specialite = request.POST.get('specialite')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_type ='enseignant'
        
        try:
           validate_email(email)
        except ValidationError:
            error = True
            message = "Veuillez entrer un email valide !"

        User = get_user_model()
        
        user = User.objects.filter(email=email).first()
        existing_user = User.objects.filter(matricule=matricule).first()

        if existing_user:
            error = True
            message = f"Le matricule {matricule} existe déjà !"
            
        if user:
            error = True
            message = f"Un utilisateur avec l'email: {email} existe déjà !"

        # Créer un nouvel objet Scolarite
        enseignant = EnseignantModels.objects.create(
            matricule=matricule, 
            username=username,
            prenom=prenom,specialite=specialite, 
            email=email,
            user_type=user_type, 
            password=password
            )
    
        enseignant.save()
        messages.success(request, 'Enseignant bien ajouté !')
        
        # Rediriger vers une autre vue ou un autre URL
        return redirect('userprincipale:enseignant')
    else:
        # Afficher le formulaire vide
        context = {'message': message, 'error': error}
        return render(request, "Enseignant/ajouter.html",context)
    
   
def editer(request, matricule):
    enseignant = get_object_or_404(EnseignantModels, matricule=matricule)
    
    if request.method == 'POST':
        # Créer un formulaire de modification et pré-remplir avec les données actuelles de la scolarité
        form = EnseignantForm(request.POST, instance=enseignant)
        if form.is_valid():
            form.save()
            return redirect('userprincipale:enseignant')
    else:
        # Afficher le formulaire pré-rempli
        form = EnseignantForm(instance=enseignant)
    
    return render(request, 'Enseignant/edit.html', {'form': form})

def supprimer(request, matricule):
    if request.method == 'POST':
        enseignant = get_object_or_404(EnseignantModels, matricule=matricule)
        enseignant.delete()
    return HttpResponseRedirect(reverse('userprincipale:enseignant'))

#scolarite
def scolarity(request):
    query=request.GET.get('qs')
    if query:
        scolarites = ScolariteModels.objects.filter(
            Q(matricule__icontains=query) |
            Q(username__icontains=query) |
            Q(prenom__icontains=query) |
            Q(fonction__icontains=query) |
            Q(etablissement__icontains=query)
        )
    else:
        scolarites = ScolariteModels.objects.all()
        
    message=messages.get_messages(request)
    
    context = {'scolarites': scolarites,'message': message}
    return render(request, "Scolarite/scolarity.html", context)

def sc_ajouter(request):
   # Verifier si le formulaire a ete soumis
    error = False
    message = ""
    if request.method == 'POST':
        
        # Récupérer les données soumises par l'utilisateur
        matricule = request.POST.get('matricule')
        username = request.POST.get('username')
        prenom = request.POST.get('prenom')
        email = request.POST.get('email')
        password = request.POST.get('password')
        fonction = request.POST.get('fonction')
        etablissement = request.POST.get('etablissement')
        user_type='scolarite'
        
        try:
           validate_email(email)
        except ValidationError:
            error = True
            message = "Veuillez entrer un email valide !"

        User = get_user_model()
        
        user = User.objects.filter(email=email).first()
        existing_user = User.objects.filter(matricule=matricule).first()

        if existing_user:
            error = True
            message = f"Le matricule {matricule} existe déjà !"
            
        if user:
            error = True
            message = f"Un utilisateur avec l'email: {email} existe déjà !"

        # Créer un nouvel objet Scolarite
        scolarite = ScolariteModels.objects.create(
            matricule=matricule,                                      
            username=username,
            prenom=prenom, 
            email=email, 
            password=password, 
            fonction=fonction,
            user_type=user_type, 
            etablissement=etablissement
            )
        scolarite.save()
        messages.success(request, 'Scolarité bien ajoutée !')
        
        # Rediriger vers une autre vue ou un autre URL
        return redirect('userprincipale:scolarity')
    else:
        # Afficher le formulaire vide
        context = {'message': message, 'error': error}
        return render(request, 'Scolarite/sc_ajouter.html',context)
    

def sc_editer(request, matricule):
    scolarite = get_object_or_404(ScolariteModels, matricule=matricule)
    
    if request.method == 'POST':
        # Créer un formulaire de modification et pré-remplir avec les données actuelles de la scolarité
        form = ScolariteForm(request.POST, instance=scolarite)
        if form.is_valid():
            form.save()
            return redirect('userprincipale:scolarite')
    else:
        # Afficher le formulaire pré-rempli
        form = ScolariteForm(instance=scolarite)
    
    return render(request, 'Scolarite/sc_edit.html', {'form': form})
    

def sc_supprimer(request, matricule):
    
    if request.method == 'POST':
       
        scolarite = ScolariteModels.objects.get(matricule=matricule)
        scolarite.delete()
       
    return HttpResponseRedirect(reverse('userprincipale:scolarity'))

#user profil
def usersprofile(request):

    return render(request, "Profil/users_profile.html")

#Afficher les etudiants sur le dashbord de l'administrateur+
def etudiant(request):
    query = request.GET.get('qe')
    if query:
        etudiants = EtudiantModels.objects.filter(
      
                Q(matricule__icontains=query) |
                Q(username__icontains=query) |
                Q(prenom__icontains=query) |
                Q(etudiant_filiere__icontains=query) |
                Q(etudiant_niveau__icontains=query) |
                Q(etudiant_promotion__icontains=query)
            
        )
    else:
        etudiants = EtudiantModels.objects.filter()

    message = messages.get_messages(request)

    context = {'etudiants': etudiants, 'message': message}
    return render(request, "Etudiant/etudiant_list.html", context)

def Admin_static(request):
    # Récupérer le nombre d'enseignants, de scolarités et d'étudiants
    nombre_enseignants = EnseignantModels.objects.count()
    nombre_etudiants = EtudiantModels.objects.count()
    nombre_scolarites = ScolariteModels.objects.count()

    # Passer les données au template
    context = {
        'nombre_enseignants': nombre_enseignants,
        'nombre_etudiants': nombre_etudiants,
        'nombre_scolarites': nombre_scolarites,
    }
    print(context)
    return render(request, "userprincipale/index.html", context)

UserPrincipale/templates/Scolarite/sc_ajouter.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Dashboard Admin {% endblock %}

{% block content %}

    <style>
    /* Style pour les labels */
    label {
        font-weight: bold;
        color: #333;
        /* Changer la couleur selon vos préférences */
    }
    </style>

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:index' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:scolarity' %}">
                <i class="bi bi-people"></i>
                <span>Scolarités</span>
            </a>
        </li><!-- End Forms Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:enseignant' %}">
                <i class="bi bi-people"></i>
                <span>Enseignants</span>
            </a>
        </li><!-- End Tables Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:usersprofile' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

    </aside><!-- End Sidebar-->

    <main id="main" class="main">

        <div class="pagetitle">
            <h6><span class="d-none d-lg-block">Gestion de copies d'étudiants de l'Université Norbert ZONGO</span></h6>
        
            <h1>Administrateur du site</h1>
            <nav>
            
                <ol class="breadcrumb">
                 <li class="breadcrumb-item active">Dashboard-Admin</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->
        <section class="section profile">
            <div class="container mt-5">
                <div class="container mt-5">
                    <h2>Ajouter une scolarité</h2>
                    {% if error %}
                    <div class="alert alert-danger" role="alert" data-mdb-color="danger">
                      {{message}}
                    </div>
                  {% endif %}
                    <form class="p-4 shadow" action="{% url 'userprincipale:sc_ajouter' %}" style="width: 50%;" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="Matricule" class="form-label">Matricule</label>
                            <input type="text" name="matricule" class="form-control" id="Matricule" required>
                            <div class="invalid-feedback">Veuillez entrer le matricule svp!</div>
                        </div>
                    
                        <div class="mb-3">
                            <label for="Nom" class="form-label">Nom</label>
                            <input type="text" name="username" class="form-control" id="Nom" required>
                            <div class="invalid-feedback">Veuillez entrer le nom svp!</div>
                        </div>
                    
                        <div class="mb-3">
                            <label for="Prenom" class="form-label">Prénom(s)</label>
                            <input type="text" name="prenom" class="form-control" id="Prenom" required>
                            <div class="invalid-feedback">Veuillez entrer le prénom svp!</div>
                        </div>
                    
                        <div class="mb-3">
                            <label for="Fonction" class="form-label">Emploi/Fonction</label>
                            <select id="form3Example3c" class="form-control" name="fonction" required>
                                    <option value="" disabled selected>Choisir la scolarité</option>
                                    <option value="CASU-Chef de scolarité">CASU-Chef de scolarité</option>
                                    <option value="CASU">CASU</option>
                                    <option value="AASU">AASU</option>
                                    <option value="Stagiaire">Stagiaire</option>
                                    <!-- Ajoutez d'autres options ici -->
                            </select>
                            <div class="invalid-feedback">Veuillez remplir le champ emploi/fonction svp!</div>
                        </div>

                        {% comment %} <div class="d-flex flex-row align-items-center mb-4">
                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                            
                        </div> {% endcomment %}
                        
                        <div class="mb-3">
                            <label for="Etablissement" class="form-label">Scolarité</label>
                            <div data-mdb-input-init class="form-outline flex-fill mb-0">
                                <select id="form3Example3c" class="form-control" name="etablissement" required>
                                    <option value="" disabled selected>Choisir la scolarité</option>
                                    <option value="UFR-ST">UFR-ST</option>
                                    <option value="UFR-SEG">UFR-SEG</option>
                                    <option value="UFR-LSH">UFR-LSH</option>
                                    <option value="IUT">IUT</option>
                                    <!-- Ajoutez d'autres options ici -->
                                </select>
                            </div>
                            <div class="invalid-feedback">Veuillez entrer la scolarité!</div>
                        </div>
                    
                        <div class="mb-3">
                            <label for="Email" class="form-label">E-mail</label>
                            <input type="email" name="email" class="form-control" id="Email" required>
                            <div class="invalid-feedback">Veuillez entrer le champ email!</div>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Mot de pass</label>
                            <input type="password" name="password" class="form-control" id="Email" required>
                            <div class="invalid-feedback">Veuillez entrer le champ mot!</div>
                        </div>
                    
                    
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary shadow">
                                <i class="bi bi-plus"></i> Ajouter
                            </button>
                        </div>
                    </form>                    

                  </div>
        </section>

    </main><!-- End #main -->

{% endblock %}

UserPrincipale/templates/Scolarite/sc_edit.html
{% extends 'base.html' %}
{% load form_tags %}

{% block title %} Dashboard Admin {% endblock %}

{% block content %}
    <style>
        /* Style pour les labels */
        label {
            font-weight: bold;
            color: #333;
            /* Changer la couleur selon vos préférences */
        }
    </style>

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
    
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'userprincipale:index' %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->
    
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                    <i class="bi bi-house-check"></i>
                    <span>Accueil</span>
                </a>
            </li><!-- End Components Nav -->
    
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'userprincipale:scolarity' %}">
                    <i class="bi bi-people"></i>
                    <span>Scolarités</span>
                </a>
            </li><!-- End Forms Nav -->
    
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'userprincipale:enseignant' %}">
                    <i class="bi bi-people"></i>
                    <span>Enseignants</span>
                </a>
            </li><!-- End Tables Nav -->
    
            <li class="nav-heading">Pages</li>
    
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'userprincipale:usersprofile' %}">
                    <i class="bi bi-person"></i>
                    <span>Mon Profil</span>
                </a>
            </li><!-- End Profile Page Nav -->
    
        </ul>
    
    </aside><!-- End Sidebar-->

        <div class="pagetitle">
            <h1>Modifier</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'userprincipale:scolarity' %}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard-Scolarité</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section profile">
            <div class="container mt-5">
                <h2>Modifier une scolarité</h2>
                <form class="p-4 shadow" style="width: 50%;" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="Matricule" class="form-label">Matricule</label>
                        {{ form.matricule|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez entrer le matricule svp!</div>
                    </div>
        
                    <div class="mb-3">
                        <label for="nom" class="form-label">Nom</label>
                        {{ form.username|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez entrer le nom svp!</div>
                    </div>
        
                    <div class="mb-3">
                        <label for="prenom" class="form-label">Prénom(s)</label>
                        {{ form.prenom|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez entrer le prénom svp!</div>
                    </div>
        
                    <div class="mb-3">
                        <label for="fonction" class="form-label">Emploi/Fonction</label>
                        {{ form.fonction|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez remplir le champ emploi/fonction svp!</div>
                    </div>
        
                    <div class="mb-3">
                        <label for="etablissement" class="form-label">Scolarité</label>
                        {{ form.etablissement|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez entrer la scolarité!</div>
                    </div>
        
                    <div class="mb-3">
                        <label for="email" class="form-label">E-mail</label>
                        {{ form.email|add_class:"form-control" }}
                        <div class="invalid-feedback">Veuillez entrer le champ email!</div>
                    </div>
        
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary shadow">
                            <i class="bi bi-plus"></i> Modifier
                        </button>
                    </div>
                </form>
            </div>
        </section>

{% endblock %}

UserPrincipale/templates/Scolarite/scolarity.html
{% extends 'base.html' %}

{% block title %}Dashboard Admin{% endblock %}

{% block content %}
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:index' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:scolarity' %}">
                <i class="bi bi-people"></i>
                <span>Scolarités</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:enseignant' %}">
                <i class="bi bi-people"></i>
                <span>Enseignants</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:etudiant' %}">
                <i class="bi bi-people"></i>
                <span>Étudiants</span>
            </a>
        </li>
        <li class="nav-heading">Pages</li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'userprincipale:usersprofile' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li>
    </ul>
</aside>

<main id="main" class="main">
    <div class="pagetitle">
        <h1>Scolarité</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'userprincipale:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Scolarité</li>
            </ol>
        </nav>
    </div>

    <section class="section profile">
        <div class="container mt-5">
            <h2>Gestion des scolarités</h2>
            <div class="row justify-content-start mb-4">
                <div class="col-auto">
                    <form method="GET" action="{% url 'userprincipale:scolarity' %}">
                        <div class="input-group">
                            <input type="text" name="qs" class="form-control" placeholder="Rechercher par matricule, nom ou spécialité" value="{{ request.GET.q }}">
                            <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i> Rechercher</button>
                        </div>
                    </form>
                </div>
                <div class="col-auto">
                    <a href="{% url 'userprincipale:sc_ajouter' %}" class="btn btn-primary shadow">
                        <i class="bi bi-plus"></i> Ajouter
                    </a>
                </div>
            </div>
        </div>

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Matricule</th>
                    <th>Nom</th>
                    <th>Prénom(s)</th>
                    <th>Emploi/Fonction</th>
                    <th>Scolarité</th>
                    <th>E-mail</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for scolarite in scolarites %}
                    <tr>
                        <td>{{ scolarite.matricule }}</td>
                        <td>{{ scolarite.username }}</td>
                        <td>{{ scolarite.prenom }}</td>
                        <td>{{ scolarite.fonction }}</td>
                        <td>{{ scolarite.etablissement }}</td>
                        <td>{{ scolarite.email }}</td>
                        <td>
                            <a href="{% url 'userprincipale:sc_editer' scolarite.matricule %}" class="btn btn-warning shadow btn-sm">
                                <i class="bi bi-pencil"></i> Modifier
                            </a>
                            <form action="{% url 'userprincipale:sc_supprimer' scolarite.matricule %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    <i class="bi bi-trash"></i> Supprimer
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if not scolarites %}
            <p>Aucune scolarité trouvée.</p>
        {% endif %}
    </section>
</main>
{% endblock %}