Authentification/urls.py
from django.urls import path
from django.urls import include
from .import views
from .views import CustomLoginView

app_name='Authentification'

urlpatterns = [
    #login
    path('login',CustomLoginView.as_view(), name='login'),
   
    #signup
    path('register', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('',views.home, name='home'),
    # path('admin/login/', CustomLoginView.as_view(), name='login'),
    
    path('profil/', views.profil_view, name='profil'),
]

Etudiant/urls.py
from django.urls import path
from .import views
app_name="Etudiant"
urlpatterns=[
    path('',views.index,name='index'),
    path('Mes_copies',views.Mes_copies,name='Mes_copies'),
    path('Fichier_Personnel',views.Fichier_Personnel,name='Fichier_Personnel'),
    path('Profil',views.Profil,name='Profil'),
    
]

ScolaritePersonal/urls.py
from django.urls import path
from .import views
app_name="ScolaritePersonal"
urlpatterns=[
    path('',views.index,name='index'),
    path('envoyer',views.envoyer,name='envoyer'),
    path('copie_corrigee',views.copie_corrigee,name='copie_corrigee'),
    path('copie_envoyee',views.copie_envoyee,name='copie_envoyee'),
    path('Profil',views.Profil,name='Profil'),
    path('get_enseignant_details/', views.get_enseignant_details, name='get_enseignant_details'),
    path('send_student',views.upload_and_link_files,name='send_student'),
    path('statistiq',views.statistiques_enseignant,name='statistiq'),
]

ScolaritePersonal/models.py
from django.db import models
from Authentification.models import CustomUser
from django.db import models
from django.contrib.auth.hashers import make_password
from django.contrib.auth import get_user_model

from Enseignant.models import EnseignantModels



# Create your models here.

    #Scolarite
class ScolariteModels(CustomUser):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='scolarite_profile', default=None, blank=True, null=True)    
    fonction = models.CharField(max_length=100, verbose_name='Emploi/Fonction')
    etablissement = models.CharField(max_length=100)
    
    class Meta:
        verbose_name = "Scolarite"
        verbose_name_plural = "Scolarites"

    def save(self, *args, **kwargs):
        if not self.pk:  # Lors de la création initiale
            self.password = make_password(self.password)
        super(ScolariteModels, self).save(*args, **kwargs)
        
class DossierImageTif(models.Model):
    enseignant = models.ForeignKey(EnseignantModels, on_delete=models.CASCADE,default =None,null=True)
    scolarite = models.ForeignKey(ScolariteModels, on_delete=models.CASCADE, default='', blank=True, null=True)
    
    enseignant_nom = models.CharField(max_length=100,default='')
    enseignant_prenom = models.CharField(max_length=100,default='')
    module = models.CharField(max_length=100, verbose_name='Module',default='')
    promotion = models.CharField(max_length=100,verbose_name='Promotion',default='')
    niveau = models.CharField(max_length=100, verbose_name='Niveau',default='')
    nombre = models.IntegerField(verbose_name='Nombre de copies',default='')
    dossier = models.FileField(upload_to='uploads/', max_length=100)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.dossier.name} - {self.enseignant.username} {self.enseignant.prenom}"

ScolaritePersonal/forms.py
# forms.py
from datetime import datetime
from django import forms
from django.forms.widgets import ClearableFileInput

from Enseignant.models import EnseignantModels
from Etudiant.models import StudentFile
from .models import DossierImageTif

class DossierImageForms(forms.Form):
    MODULE_CHOICES = [
        ('Statistique', 'Statistique'),
        ('Algèbre', 'Algèbre'),
        ('Analyse', 'Analyse'),
        ('Programmation Orientée Objet', 'Programmation Orientée Objet'),
        ('Thermodynamique', 'Thermodynamique'),
        ('Problabilité', 'Problabilité'),
        ('Algorithemique', 'Algorithemique'),
    ]

    PROMOTION_CHOICES = [
        ('MPCI - 2020-2021', 'MPCI - 2020-2021'),
        ('Informatique - 2020-2021', 'Informatique - 2020-2021'),
        ('SVT - 2019-2020', 'SVT - 2019-2020'),
        ('Lettre moderne - 2020-2021', 'Lettre moderne - 2020-2021'),
        ('Allemand - 2017-2018', 'Allemand - 2017-2018'),
    ]

    NIVEAU_CHOICES = [
        ('L1', 'L1'),
        ('L2', 'L2'),
        ('L3', 'L3'),
        ('M1', 'M1'),
        ('M2', 'M2'),
    ]
    UFR_CHOICES = [('Choisir ','Choisir'), 
        ('UFR-SEG', 'UFR-SEG'), ('UFR-ST', 'UFR-ST'),
        ('UFR-LSH', 'UFR-LSH'),
        ('IUT', 'IUT'),
    ]
    promotion = forms.ChoiceField(choices=PROMOTION_CHOICES)
    module = forms.ChoiceField(choices=MODULE_CHOICES)
    niveau = forms.ChoiceField(choices=NIVEAU_CHOICES)
    nombre =forms.IntegerField(label='Nombre de copies')
    enseignant_nom_prenom = forms.ModelChoiceField(
        queryset=EnseignantModels.objects.all(),
        to_field_name='matricule',
        label="Enseignant (Nom et prénom)",
        widget=forms.Select)
    

    date = forms.DateTimeField(initial=datetime.now, widget=forms.HiddenInput())  
    
    # def __init__(self, *args, **kwargs):
    #     super(DossierImageForms, self).__init__(*args, **kwargs)
    #     self.fields['enseignant_matricule'].choices = [(e.matricule, f"{e.username} {e.prenom}") for e in EnseignantModels.objects.all()]  
    class meta:
        model = DossierImageTif
        fields = ['dossier']
        widgets = {
            'dossier': ClearableFileInput(attrs={'allow_multiple_selected': True, 'class': 'form-control'})
        }
        
class UploadFileForm(forms.Form):
    MODULE_CHOICES = [
        ('Statistique', 'Statistique'),
        ('Algèbre', 'Algèbre'),
        ('Analyse', 'Analyse'),
        ('POO', 'POO'),
        ('Algorithemique', 'Algorithemique'),
    ]
    module = forms.ChoiceField(choices=MODULE_CHOICES)
    
    class meta:
        model: StudentFile
        fields = ['fichier']
        widgets = {
            'file': ClearableFileInput(attrs={'allow_multiple_selected': True, 'class': 'form-control'})
        }

ScolaritePersonal/views.py
from django.utils import timezone
from django.core.files.base import ContentFile
import zipfile
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from GestionDesCopies import settings
from ScolaritePersonal.models import DossierImageTif, ScolariteModels
from Enseignant. models import EnseignantModels
from .forms import DossierImageForms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
import logging
import re
from Etudiant.models import StudentFile, EtudiantModels
from .forms import UploadFileForm
from django.db.models import Sum
logger = logging.getLogger(__name__)

#from Enseignant.models import EnseignantModel


# Create your views here.
@login_required(login_url='Authentification:login')
def index (request):
     # Récupérer l'utilisateur connecté (scolarite)
    scolarite = request.user

    # Récupérer les copies reçues par la scolarité
    copies_recues = DossierImageTif.objects.filter(scolarite=scolarite).order_by('-date')

    context = {
        'copies_recues': copies_recues
    }
    
    return render(request,"ScolaritePersonal/index.html",context)


def handle_uploaded_files(files, folder_path):
    zip_subfolder_path = os.path.join(folder_path, 'copies.zip')
    with zipfile.ZipFile(zip_subfolder_path, 'w') as zipf:
        for f in files:
            file_path = os.path.join(folder_path, f.name)
            with open(file_path, 'wb+') as destination:
                for chunk in f.chunks():
                    destination.write(chunk)
            zipf.write(file_path, os.path.basename(file_path))
            os.remove(file_path)  # Optionally remove the original files
    return zip_subfolder_path

@login_required(login_url='Authentification:login')
def envoyer(request):
    if request.method == 'POST':
        form = DossierImageForms(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('dossier')
            enseignant_matricule = form.cleaned_data['enseignant_matricule']
            
            try:
                enseignant = EnseignantModels.objects.get(matricule=enseignant_matricule)
            except EnseignantModels.DoesNotExist:
                message = f"Aucun enseignant trouvé avec le matricule {enseignant_matricule}."
                return render(request, 'copie/copie_envoyee.html', {'message': message})

            # Crée un dossier pour l'enseignant
            folder_name = f'{enseignant_matricule}_{enseignant.username}'
            folder_path = os.path.join(settings.MEDIA_ROOT, 'uploads', folder_name)

            if not os.path.exists(folder_path):
                os.makedirs(folder_path)

            # Gérer le fichier uploadé
            zip_file_path = handle_uploaded_files(files, folder_path)

            # Obtenir l'instance de ScolariteModels de l'utilisateur connecté
            
            #scolarite = ScolariteModels.objects.get(user=request.user)
            
                # message = 'Aucune scolarité associée à cet utilisateur.'
                # return render(request, 'copie/copie_envoyee.html', {'message': message})
            
            #logger.debug(f'Scolarite: {scolarite}')

            # Créer l'objet DossierImageTif
            DossierImageTif.objects.create(
                dossier=ContentFile(open(zip_file_path, 'rb').read(), 'copies.zip'),
                enseignant=enseignant,
                module=form.cleaned_data['module'],
                promotion=form.cleaned_data['promotion'],
                niveau=form.cleaned_data['niveau'],
                nombre=form.cleaned_data['nombre'],
                date=timezone.now(),
            )
            # Message de succès
            success_message = f"Copie envoyée avec succès à {enseignant.username} {enseignant.prenom}."
            messages.success(request, success_message)
        else:
            messages.error(request, "Veuillez vérifier les informations du formulaire.")
    else:
        form = DossierImageForms()

    return render(request, "copie/envoyer_copie.html", {'form': form})

@login_required(login_url='Authentification:login')
def statistiques_enseignant(request):
   # Nombre d'enseignants ayant reçu des copies de la scolarité
    total_enseignants = DossierImageTif.objects.filter(scolarite=request.user.scolarite).values('enseignant').distinct().count()

    # Nombre total de copies envoyées par la scolarité
    total_copies = DossierImageTif.objects.filter(scolarite=request.user_type.scolarite).aggregate(total_copies=Sum('nombre'))['total_copies']

    # Nombre de modules non corrigés pour les copies envoyées par la scolarité
    total_modules = DossierImageTif.objects.filter(scolarite=request.user_type.scolarite).values('module').distinct().count()

    context = {
        'total_enseignants': total_enseignants,
        'total_copies': total_copies,
        'total_modules': total_modules,
    }

    return render(request, "ScolaritePersonal/index.html", context)


@login_required
def get_enseignant_details(request):
    
    enseignants = EnseignantModels.objects.all()
    enseignants_json = list(enseignants.values('matricule', 'username', 'prenom'))
    
    return JsonResponse(enseignants_json, safe=False)
@login_required
def copie_corrigee (request):
    
        return render (request,'copie/copie_corrigee.html')

@login_required
def copie_envoyee(request):
    try:
        # Récupérer l'utilisateur connecté (scolarité)
        scolarite = ScolariteModels.objects.get(user=request.user)
    except ScolariteModels.DoesNotExist:
        # Si aucune instance n'est trouvée, rediriger ou gérer l'erreur
        message = 'Aucune scolarité associée à cet utilisateur.'
        context = {'message': message} 
        return render(request, 'copie/copie_envoyee.html', context)
    
    # Récupérer les copies envoyées par cette scolarité
    copies_envoyees = DossierImageTif.objects.filter(scolarite=scolarite).order_by('-date')

    # Pagination des copies
    paginator = Paginator(copies_envoyees, 10)  # 10 copies par page

    page_number = request.GET.get('page')
    try:
        copies = paginator.page(page_number)
    except PageNotAnInteger:
        # Si la page n'est pas un entier, renvoyer la première page.
        copies = paginator.page(1)
    except EmptyPage:
        # Si la page est hors limites, renvoyer la dernière page de résultats.
        copies = paginator.page(paginator.num_pages)

    context = {
        'copies': copies,
        'scolarite': scolarite,
    }

    return render(request, 'copie/copie_envoyee.html', context)


@login_required
def Profil (request):
    
    return render(request,"Profil/scolarite_profil.html") 


@login_required
def upload_and_link_files(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES.getlist('fichier')
            module = form.cleaned_data['module']
            upload_dir = os.path.join(settings.MEDIA_ROOT, 'student_files')

            # Créer le répertoire si nécessaire
            if not os.path.exists(upload_dir):
                os.makedirs(upload_dir)

            for file in files:
                file_path = os.path.join(upload_dir, file.name)  # Assurez-vous du chemin ici

                with open(file_path, 'wb+') as destination:
                    for chunk in file.chunks():
                        destination.write(chunk)

                if zipfile.is_zipfile(file_path):
                    extracted_path = os.path.join(upload_dir, 'extracted')
                    with zipfile.ZipFile(file_path, 'r') as zip_ref:
                        zip_ref.extractall(extracted_path)
                    os.remove(file_path)  # Supprimez le fichier zip après extraction

                    for filename in os.listdir(extracted_path):
                        if filename.endswith('.pdf'):
                            link_file_to_student(os.path.join('student_files', 'extracted', filename), module)
                else:
                    if file.name.endswith('.pdf'):
                        link_file_to_student(os.path.join('student_files', file.name), module)

            return redirect('ScolaritePersonal:send_student')  # Rediriger vers le tableau de bord ou une autre page après l'upload
    else:
        form = UploadFileForm()
    return render(request, 'copie/Student_copie.html', {'form': form})

def link_file_to_student(file_path, module):
    filename = os.path.basename(file_path)
    matricule_match = re.search(r'([EN]\d{11})', filename)  # Match matricules commençant par E ou N suivis de 11 chiffres
    if matricule_match:
        matricule = matricule_match.group(1)
        try:
            student = EtudiantModels.objects.get(matricule=matricule)
            student_file = StudentFile(student=student, fichier=file_path, module=module)
            student_file.save()
        except EtudiantModels.DoesNotExist:
            # Gérez le cas où aucun étudiant avec ce matricule n'existe
            pass

ScolaritePersonal/templates/ScolaritePersonal/index.html
{% extends "base.html" %}

{% block title %} Dashboard Scolarité {% endblock %}

{% block content %}
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:index' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'Authentification:login' %}">
                <i class="bi bi-house-check"></i>
                <span>Accueil</span>
            </a>
        </li><!-- End Components Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:envoyer' %}">
                <i class="bi bi-files"></i>
                <span>Envoyer|Enseignant</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:send_student' %}">
                <i class="bi bi-files"></i>
                <span>Envoyer|Etudiant</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:copie_envoyee' %}">
                <i class="bi bi-files"></i>
                <span>Copies envoyées</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:copie_corrigee' %}">
                <i class="bi bi-files"></i>
                <span>Copies corrigées</span>
            </a>
        </li><!-- End Forms Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'ScolaritePersonal:Profil' %}">
                <i class="bi bi-person"></i>
                <span>Mon Profil</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->

<main id="main" class="main">

    <div class="pagetitle">
        <h6><span class="d-none d-lg-block">Gestion de copies d'étudiants de l'Université Norbert ZONGO</span></h6>
        
        <h1>Scolarite de l'UFR-ST</h1>
        <nav>
            
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'ScolaritePersonal:index' %}">Home</a></li>
                <li class="breadcrumb-item active">Dashboard-Scolarite</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">

            <!-- Left side columns -->
            <div class="col-lg-12">
                <div class="row">

                    <!-- Sales Card -->
                    <div class="col-xxl-4 col-md-6">
                        <div class="card info-card sales-card">
                
                            <div class="card-body">
                                <h5 class="card-title">Copies <span>| Nombre</span></h5>

                                <div class="d-flex align-items-center">
                                    <div
                                        class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                        <i class="bi bi-copy"></i>
                                    </div>
                                    <div class="ps-3">
                                        <h6>{{ total_copies }}</h6> 
                                        <span class="text-muted small pt-2 ps-1">Envoyées aux enseignants </span> 
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div><!-- End Sales Card -->

                    <!-- Revenue Card -->
                    <div class="col-xxl-4 col-md-6">
                        <div class="card info-card revenue-card">
                            
                            <div class="card-body">
                                <h5 class="card-title">Enseignants <span>| Nombre</span></h5>

                                <div class="d-flex align-items-center">
                                    <div
                                        class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                        <i class="bi bi-people"></i>
                                    </div>
                                    <div class="ps-3">
                                        <h6>{{ total_enseignants }}</h6>
                                        <span class="text-muted small pt-2 ps-1">Ayant reçcu des copies </span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-xxl-4 col-md-6">
                        <div class="card info-card revenue-card">
                            
                            <div class="card-body">
                                <h5 class="card-title">Modules <span>| Nombre</span></h5>

                                <div class="d-flex align-items-center">
                                    <div
                                        class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                        <i class="bi bi-files"></i>
                                    </div>
                                    <div class="ps-3">
                                        <h6>{{ total_modules }}</h6>
                                        <span class="text-muted small pt-2 ps-1">envoyé </span>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div><!-- End Revenue Card -->
                 
                    <!-- Recent Sales -->
                    
                    <!-- Recent Sales -->
                    <div class="col-12">
                        <div class="card recent-sales overflow-auto">
                            <div class="card-body">
                                <h5 class="card-title">Copies corigées </h5>

                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Promotion</th>
                                            <th scope="col">Module</th>
                                            <th scope="col">Niveau</th>
                                            {% comment %} <th scope="col">UFR</th> {% endcomment %}
                                            <th scope="col">Nombre de copies</th>
                                            <th scope="col">Date d'envoi</th>
                                            <th scope="col">Téléchargement</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for copie in copies_recues %}
                                        <tr>
                                            <td>{{ copie.promotion }}</td>
                                            <td>{{ copie.module }}</td>
                                            <td>{{ copie.niveau }}</td>
                                            {% comment %} <td>{{ copie.ufr }}</td> {% endcomment %}
                                            <td>{{ copie.nombre }}</td>
                                            <td>{{ copie.date|date:"d/m/Y H:i" }}</td>
                                            <td><a href="{{ copie.dossier.url }}" class="badge bg-danger" download>Télécharger</a></td>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="7">Aucune copie reçue.</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!-- Pagination example -->
                                <!-- Replace with your own pagination implementation -->
                                <div class="dataTables_paginate paging_simple_numbers" id="dataTable_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button page-item previous disabled" id="dataTable_previous">
                                            <a href="#" aria-controls="dataTable" tabindex="0" class="page-link">Précedent</a>
                                        </li>
                                        <!-- Pagination items here -->
                                        <li class="paginate_button page-item next" id="dataTable_next">
                                            <a href="#" aria-controls="dataTable" tabindex="0" class="page-link">Suivant</a>
                                        </li>
                                    </ul>
                                </div>       
                </div>
            </div><!-- End Left side columns -->
        </div>
    </section>

</main><!-- End #main -->
   
{% endblock %}